directories:
  mirror_module_path: False
  base: "textmp"
  subdirs:
    output: "videos"
    raster_images: "raster_images"
    vector_images: "vector_images"
    sounds: "sounds"
    data: "data"
    downloads: "downloads"
  cache: "textmp"
window:
  position_string: OO
  monitor_index: 0
  full_screen: False
  size: (1280, 720)  # Specific size, in pixels
camera:
  resolution: (1920, 1080)
  background_color: "#333333"
  fps: 60
  background_opacity: 1.0
file_writer:
  # 在新版本中去除了
  # break_into_partial_movies: False
  ffmpeg_bin: "ffmpeg"
  video_codec: "libx264"
  pixel_format: "yuv420p"
  saturation: 1.0
  gamma: 1.0
scene:
  show_animation_progress: False
  leave_progress_bars: False
  default_wait_time: 1.0
vmobject:
  default_stroke_width: 4.0
tex:
  # See tex_templates.yml
  template: "ctex"
  mainfont: "SimSon"
text:
  font: "Consolas"
  alignment: "LEFT"
sizes:
  frame_height: 8.0
  small_buff: 0.1
  med_small_buff: 0.25
  med_large_buff: 0.5
  large_buff: 1.0
  default_mobject_to_edge_buff: 0.5
  default_mobject_to_mobject_buff: 0.25
# Can be DEBUG / INFO / WARNING / ERROR / CRITICAL
log_level: "INFO"
ignore_manimlib_modules_on_reload: True
